
package edu.depaul.se457;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QuoteServiceImplmentation", targetNamespace = "http://se457.depaul.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuoteServiceImplmentation {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addQuote", targetNamespace = "http://se457.depaul.edu/", className = "edu.depaul.se457.AddQuote")
    @ResponseWrapper(localName = "addQuoteResponse", targetNamespace = "http://se457.depaul.edu/", className = "edu.depaul.se457.AddQuoteResponse")
    @Action(input = "http://se457.depaul.edu/QuoteServiceImplmentation/addQuoteRequest", output = "http://se457.depaul.edu/QuoteServiceImplmentation/addQuoteResponse")
    public void addQuote(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://se457.depaul.edu/", className = "edu.depaul.se457.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://se457.depaul.edu/", className = "edu.depaul.se457.GetQuoteResponse")
    @Action(input = "http://se457.depaul.edu/QuoteServiceImplmentation/getQuoteRequest", output = "http://se457.depaul.edu/QuoteServiceImplmentation/getQuoteResponse")
    public String getQuote();

}
